// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffeeMaker.proto

package io.grpc.examples.oven;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coffeeMaker.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
