// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.examples.lights;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.Empty)
    com.google.protobuf.MessageOrBuilder {
}
