// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.examples.lights;

public final class LightsServiceImpl {
  private LightsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_SintRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_SintRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lights.proto\022\006lights\"\036\n\016StringResponse" +
      "\022\014\n\004text\030\001 \001(\t\"\034\n\013SintRequest\022\r\n\005value\030\001" +
      " \001(\021\"\007\n\005Empty2\303\001\n\rLightsService\0225\n\014toggl" +
      "eLights\022\r.lights.Empty\032\026.lights.StringRe" +
      "sponse\0228\n\017getLightsStatus\022\r.lights.Empty" +
      "\032\026.lights.StringResponse\022A\n\020changeLumino" +
      "sity\022\023.lights.SintRequest\032\026.lights.Strin" +
      "gResponse(\001B.\n\027io.grpc.examples.lightsB\021" +
      "LightsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lights_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lights_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_lights_SintRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lights_SintRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_SintRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_lights_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lights_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
