// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.examples.lights;

public interface SintRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.SintRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 value = 1;</code>
   */
  int getValue();
}
