# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heating.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='heating.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rheating.proto\"\x1e\n\x0eStringResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0bIntResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\nIntRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xae\x01\n\x0eHeatingService\x12,\n\x14getSystemTempSetting\x12\x06.Empty\x1a\x0c.IntResponse\x12\x38\n\x18\x63hangeSystemTempSettings\x12\x0b.IntRequest\x1a\x0f.StringResponse\x12\x34\n\x19toggleHeatingSystemStatus\x12\x06.Empty\x1a\x0f.StringResponseb\x06proto3'
)




_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='StringResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=47,
)


_INTRESPONSE = _descriptor.Descriptor(
  name='IntResponse',
  full_name='IntResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IntResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=77,
)


_INTREQUEST = _descriptor.Descriptor(
  name='IntRequest',
  full_name='IntRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IntRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=106,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['IntResponse'] = _INTRESPONSE
DESCRIPTOR.message_types_by_name['IntRequest'] = _INTREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRINGRESPONSE,
  '__module__' : 'heating_pb2'
  # @@protoc_insertion_point(class_scope:StringResponse)
  })
_sym_db.RegisterMessage(StringResponse)

IntResponse = _reflection.GeneratedProtocolMessageType('IntResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTRESPONSE,
  '__module__' : 'heating_pb2'
  # @@protoc_insertion_point(class_scope:IntResponse)
  })
_sym_db.RegisterMessage(IntResponse)

IntRequest = _reflection.GeneratedProtocolMessageType('IntRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTREQUEST,
  '__module__' : 'heating_pb2'
  # @@protoc_insertion_point(class_scope:IntRequest)
  })
_sym_db.RegisterMessage(IntRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'heating_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_HEATINGSERVICE = _descriptor.ServiceDescriptor(
  name='HeatingService',
  full_name='HeatingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=118,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSystemTempSetting',
    full_name='HeatingService.getSystemTempSetting',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_INTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='changeSystemTempSettings',
    full_name='HeatingService.changeSystemTempSettings',
    index=1,
    containing_service=None,
    input_type=_INTREQUEST,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='toggleHeatingSystemStatus',
    full_name='HeatingService.toggleHeatingSystemStatus',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEATINGSERVICE)

DESCRIPTOR.services_by_name['HeatingService'] = _HEATINGSERVICE

# @@protoc_insertion_point(module_scope)
