// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffeeMaker.proto

package io.grpc.examples.coffee_maker;

public interface BrewTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coffeeMaker.BrewType)
    com.google.protobuf.MessageOrBuilder {
}
