// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffeeMaker.proto

package io.grpc.examples.coffee_maker;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coffeeMaker.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>double progress = 2;</code>
   */
  double getProgress();
}
