// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.examples.oven;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oven.Empty)
    com.google.protobuf.MessageOrBuilder {
}
