// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.examples.oven;

public interface floatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oven.floatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   */
  float getValue();
}
