// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.examples.oven;

/**
 * Protobuf type {@code oven.OvenSetting}
 */
public  final class OvenSetting extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oven.OvenSetting)
    OvenSettingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OvenSetting.newBuilder() to construct.
  private OvenSetting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OvenSetting() {
    setting_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OvenSetting(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            setting_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.oven.OvenServiceImpl.internal_static_oven_OvenSetting_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.oven.OvenServiceImpl.internal_static_oven_OvenSetting_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.oven.OvenSetting.class, io.grpc.examples.oven.OvenSetting.Builder.class);
  }

  /**
   * Protobuf enum {@code oven.OvenSetting.Setting}
   */
  public enum Setting
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GRILL = 0;</code>
     */
    GRILL(0),
    /**
     * <code>FAN_ASSISTED = 1;</code>
     */
    FAN_ASSISTED(1),
    /**
     * <code>UNASSISTED = 2;</code>
     */
    UNASSISTED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GRILL = 0;</code>
     */
    public static final int GRILL_VALUE = 0;
    /**
     * <code>FAN_ASSISTED = 1;</code>
     */
    public static final int FAN_ASSISTED_VALUE = 1;
    /**
     * <code>UNASSISTED = 2;</code>
     */
    public static final int UNASSISTED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Setting valueOf(int value) {
      return forNumber(value);
    }

    public static Setting forNumber(int value) {
      switch (value) {
        case 0: return GRILL;
        case 1: return FAN_ASSISTED;
        case 2: return UNASSISTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Setting>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Setting> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Setting>() {
            public Setting findValueByNumber(int number) {
              return Setting.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.grpc.examples.oven.OvenSetting.getDescriptor().getEnumTypes().get(0);
    }

    private static final Setting[] VALUES = values();

    public static Setting valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Setting(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:oven.OvenSetting.Setting)
  }

  public static final int SETTING_FIELD_NUMBER = 1;
  private int setting_;
  /**
   * <code>.oven.OvenSetting.Setting setting = 1;</code>
   */
  public int getSettingValue() {
    return setting_;
  }
  /**
   * <code>.oven.OvenSetting.Setting setting = 1;</code>
   */
  public io.grpc.examples.oven.OvenSetting.Setting getSetting() {
    @SuppressWarnings("deprecation")
    io.grpc.examples.oven.OvenSetting.Setting result = io.grpc.examples.oven.OvenSetting.Setting.valueOf(setting_);
    return result == null ? io.grpc.examples.oven.OvenSetting.Setting.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (setting_ != io.grpc.examples.oven.OvenSetting.Setting.GRILL.getNumber()) {
      output.writeEnum(1, setting_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (setting_ != io.grpc.examples.oven.OvenSetting.Setting.GRILL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, setting_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.examples.oven.OvenSetting)) {
      return super.equals(obj);
    }
    io.grpc.examples.oven.OvenSetting other = (io.grpc.examples.oven.OvenSetting) obj;

    boolean result = true;
    result = result && setting_ == other.setting_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETTING_FIELD_NUMBER;
    hash = (53 * hash) + setting_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.examples.oven.OvenSetting parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.oven.OvenSetting parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.examples.oven.OvenSetting parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.oven.OvenSetting parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.examples.oven.OvenSetting prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oven.OvenSetting}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oven.OvenSetting)
      io.grpc.examples.oven.OvenSettingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.oven.OvenServiceImpl.internal_static_oven_OvenSetting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.oven.OvenServiceImpl.internal_static_oven_OvenSetting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.oven.OvenSetting.class, io.grpc.examples.oven.OvenSetting.Builder.class);
    }

    // Construct using io.grpc.examples.oven.OvenSetting.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      setting_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.oven.OvenServiceImpl.internal_static_oven_OvenSetting_descriptor;
    }

    @java.lang.Override
    public io.grpc.examples.oven.OvenSetting getDefaultInstanceForType() {
      return io.grpc.examples.oven.OvenSetting.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.examples.oven.OvenSetting build() {
      io.grpc.examples.oven.OvenSetting result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.examples.oven.OvenSetting buildPartial() {
      io.grpc.examples.oven.OvenSetting result = new io.grpc.examples.oven.OvenSetting(this);
      result.setting_ = setting_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.oven.OvenSetting) {
        return mergeFrom((io.grpc.examples.oven.OvenSetting)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.oven.OvenSetting other) {
      if (other == io.grpc.examples.oven.OvenSetting.getDefaultInstance()) return this;
      if (other.setting_ != 0) {
        setSettingValue(other.getSettingValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.examples.oven.OvenSetting parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.examples.oven.OvenSetting) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int setting_ = 0;
    /**
     * <code>.oven.OvenSetting.Setting setting = 1;</code>
     */
    public int getSettingValue() {
      return setting_;
    }
    /**
     * <code>.oven.OvenSetting.Setting setting = 1;</code>
     */
    public Builder setSettingValue(int value) {
      setting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.oven.OvenSetting.Setting setting = 1;</code>
     */
    public io.grpc.examples.oven.OvenSetting.Setting getSetting() {
      @SuppressWarnings("deprecation")
      io.grpc.examples.oven.OvenSetting.Setting result = io.grpc.examples.oven.OvenSetting.Setting.valueOf(setting_);
      return result == null ? io.grpc.examples.oven.OvenSetting.Setting.UNRECOGNIZED : result;
    }
    /**
     * <code>.oven.OvenSetting.Setting setting = 1;</code>
     */
    public Builder setSetting(io.grpc.examples.oven.OvenSetting.Setting value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      setting_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.oven.OvenSetting.Setting setting = 1;</code>
     */
    public Builder clearSetting() {
      
      setting_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oven.OvenSetting)
  }

  // @@protoc_insertion_point(class_scope:oven.OvenSetting)
  private static final io.grpc.examples.oven.OvenSetting DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.examples.oven.OvenSetting();
  }

  public static io.grpc.examples.oven.OvenSetting getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OvenSetting>
      PARSER = new com.google.protobuf.AbstractParser<OvenSetting>() {
    @java.lang.Override
    public OvenSetting parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OvenSetting(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OvenSetting> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OvenSetting> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.examples.oven.OvenSetting getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

