// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.examples.oven;

public interface OvenStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oven.OvenStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.oven.OvenStatus.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.oven.OvenStatus.Status status = 1;</code>
   */
  io.grpc.examples.oven.OvenStatus.Status getStatus();
}
