// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.examples.oven;

public interface SettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oven.Setting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.oven.Setting.Enum setting = 1;</code>
   */
  int getSettingValue();
  /**
   * <code>.oven.Setting.Enum setting = 1;</code>
   */
  io.grpc.examples.oven.OvenSetting.Setting getSetting();
}
