// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jmDnsHandler.proto

package com.jmDNS.grpc;

public interface detailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DnsServer.details)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 port = 1;</code>
   */
  int getPort();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
