// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jmDnsHandler.proto

package com.jmDNS.grpc;

public interface detailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DnsServer.details)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string path = 5;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 5;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
