// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jmDnsHandler.proto

package com.jmDNS.grpc;

public final class DnsServiceImpl {
  private DnsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnsServer_details_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnsServer_details_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnsServer_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnsServer_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022jmDnsHandler.proto\022\tDnsServer\"(\n\007detai" +
      "ls\022\014\n\004port\030\001 \001(\005\022\017\n\007address\030\002 \001(\t\"\007\n\005Emp" +
      "ty2~\n\nDnsService\0228\n\020selfRegistration\022\022.D" +
      "nsServer.details\032\020.DnsServer.Empty\0226\n\016se" +
      "lfUnregister\022\022.DnsServer.details\032\020.DnsSe" +
      "rver.EmptyB\"\n\016com.jmDNS.grpcB\016DnsService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DnsServer_details_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnsServer_details_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnsServer_details_descriptor,
        new java.lang.String[] { "Port", "Address", });
    internal_static_DnsServer_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DnsServer_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnsServer_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
