// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jmDnsHandler.proto

package com.jmDNS.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DnsServer.Empty)
    com.google.protobuf.MessageOrBuilder {
}
